SISASEPBA/SISASEPBA/Controllers/ProveedoresController.cs
using SISASEPBA.ServicioAsepba;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace SISASEPBA.Controllers
{
    public class ProveedoresController : Controller
    {
        private readonly ServicioAsepba.ServiceAsepbaClient _servicio = new ServiceAsepbaClient();
        // GET: Proveedores
        public ActionResult Index()
        {
            var dt = _servicio.ConsultarProveedor(new Proveedor
            {
                Accion = "CONSULTAR",
                FechaCreacion = DateTime.Now,
                FechaModificacion = DateTime.Now,
                FechaRige = DateTime.Now,
                FechaVence = DateTime.Now
            });

            var usr = dt.Tables[0].AsEnumerable().Select(dataRow => new Models.Proveedor
            {
                IdProveedor = dataRow.Field<int>("IDPROVEEDOR"),
                NombreReal = dataRow.Field<string>("NOMBREREAL"),
                FechaRige = dataRow.Field<DateTime>("FECHARIGE"),
                FechaVence = dataRow.Field<DateTime>("FECHAVENCE"),
                Estado = dataRow.Field<bool>("ESTADO"),

            }).ToList();
            return View(usr);
        }


        // GET: Proveedores/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Proveedores/Create
        [HttpPost]
        public ActionResult Create(Proveedor proveedor, HttpPostedFileBase doc, HttpPostedFileBase img)
        {
            try
            {
                if (doc != null && doc.ContentLength > 0)
                {
                    byte[] documentoData = null;
                    using (var documento = new BinaryReader(doc.InputStream))
                    {
                        documentoData = documento.ReadBytes(doc.ContentLength);
                    }

                    proveedor.DocumentoAdjunto = documentoData;
                }

                if (img != null && img.ContentLength > 0)
                {
                    byte[] imageData = null;
                    using (var imagen = new BinaryReader(img.InputStream))
                    {
                        imageData = imagen.ReadBytes(img.ContentLength);
                    }

                    proveedor.Logo = imageData;
                }

                var objeto = new Proveedor
                {
                    Accion = "INSERTAR",
                    NumeroCedula = proveedor.NumeroCedula,
                    NombreFantasia = proveedor.NombreFantasia,
                    NombreReal = proveedor.NombreReal,
                    PrimerNombreApoderado = proveedor.PrimerNombreApoderado,
                    SegundoNombreApoderado = proveedor.SegundoNombreApoderado,
                    PrimerApellidoApoderado = proveedor.PrimerApellidoApoderado,
                    SegundoApellidoApoderado = proveedor.SegundoApellidoApoderado,
                    CedulaApoderado = proveedor.CedulaApoderado,
                    FechaRige = proveedor.FechaRige,
                    FechaVence = proveedor.FechaVence,
                    Estado = proveedor.Estado,
                    DescripcionConvenio = proveedor.DescripcionConvenio,
                    BeneficioAsociado = proveedor.BeneficioAsociado,
                    BeneficioASEPBA = proveedor.BeneficioASEPBA,
                    DocumentoAdjunto = proveedor.DocumentoAdjunto,
                    PersonaContacto = proveedor.PersonaContacto,
                    CorreoContacto = proveedor.CorreoContacto,
                    TelefonoContacto = proveedor.TelefonoContacto,
                    SegundaPersonaContacto = proveedor.SegundaPersonaContacto,
                    CorreoSegundoContacto = proveedor.CorreoSegundoContacto,
                    TelefonoSegundoContacto = proveedor.TelefonoSegundoContacto,
                    Logo = proveedor.Logo,
                    UsuarioCreacion = User.Identity.Name,
                    FechaCreacion = DateTime.Now,
                    UsuarioModificacion = User.Identity.Name,
                    FechaModificacion = DateTime.Now
                };

                var dt = _servicio.ProcesarProveedor(objeto);

                if (dt.IsSuccess)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View("Create");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: Proveedores/Edit/5
        public ActionResult Edit(int id)
        {
            var dt = _servicio.ConsultarProveedor(new Proveedor
            {
                Accion = "CONSULTAR_PROVEEDOR",
                IdProveedor = id,
                FechaCreacion = DateTime.Now,
                FechaModificacion = DateTime.Now,
                FechaRige = DateTime.Now,
                FechaVence = DateTime.Now
            });

            var usr = dt.Tables[0].AsEnumerable().Select(dataRow => new Models.Proveedor
            {
                IdProveedor = dataRow.Field<int>("IDPROVEEDOR"),
                NumeroCedula = dataRow.Field<int>("NUMEROCEDULA"),
                NombreFantasia = dataRow.Field<string>("NOMBREFANTASIA"),
                NombreReal = dataRow.Field<string>("NOMBREREAL"),
                PrimerNombreApoderado = dataRow.Field<string>("PRIMERNOMBREAPODERADO"),
                SegundoNombreApoderado = dataRow.Field<string>("SEGUNDONOMBREAPODERADO"),
                PrimerApellidoApoderado = dataRow.Field<string>("PRIMERAPELLIDOAPODERADO"),
                SegundoApellidoApoderado = dataRow.Field<string>("SEGUNDOAPELLIDOAPODERADO"),
                CedulaApoderado = dataRow.Field<int>("CEDULAAPODERADO"),
                FechaRige = dataRow.Field<DateTime>("FECHARIGE"),
                FechaVence = dataRow.Field<DateTime>("FECHAVENCE"),
                Estado = dataRow.Field<bool>("ESTADO"),
                DescripcionConvenio = dataRow.Field<string>("DESCRIPCIONCONVENIO"),
                BeneficioAsociado = dataRow.Field<string>("BENEFICIOASOCIADO"),
                BeneficioASEPBA = dataRow.Field<string>("BENEFICIOASEPBA"),
                DocumentoAdjunto = dataRow.Field < byte[] >("DOCUMENTOADJUNTO"),
                PersonaContacto = dataRow.Field<string>("PERSONACONTACTO"),
                CorreoContacto = dataRow.Field<string>("CORREOCONTACTO"),
                TelefonoContacto = dataRow.Field<string>("TELEFONOCONTACTO"),
                SegundaPersonaContacto = dataRow.Field<string>("SEGUNDAPERSONACONTACTO"),
                CorreoSegundoContacto = dataRow.Field<string>("CORREOSEGUNDOCONTACTO"),
                TelefonoSegundoContacto = dataRow.Field<string>("TELEFONOSEGUNDOCONTACTO"),
                Logo = dataRow.Field<byte[]>("LOGO"),
                UsuarioCreacion = dataRow.Field<string>("USUARIOCREACION"),
                FechaCreacion = dataRow.Field<DateTime>("FECHACREACION")

            }).FirstOrDefault();
            return View(usr);
        }

        // POST: Proveedores/Edit/5
        [HttpPost]
        public ActionResult Edit(Proveedor proveedor, HttpPostedFileBase doc, HttpPostedFileBase img)
        {
            try
            {
                if (doc != null && doc.ContentLength > 0)
                {
                    byte[] documentoData = null;
                    using (var documento = new BinaryReader(doc.InputStream))
                    {
                        documentoData = documento.ReadBytes(doc.ContentLength);
                    }

                    proveedor.DocumentoAdjunto = documentoData;
                }

                if (img != null && img.ContentLength > 0)
                {
                    byte[] imageData = null;
                    using (var imagen = new BinaryReader(img.InputStream))
                    {
                        imageData = imagen.ReadBytes(img.ContentLength);
                    }

                    proveedor.Logo = imageData;
                }

                var objeto = new Proveedor
                {
                    Accion = "ACTUALIZAR",
                    IdProveedor = proveedor.IdProveedor,
                    NumeroCedula = proveedor.NumeroCedula,
                    NombreFantasia = proveedor.NombreFantasia,
                    NombreReal = proveedor.NombreReal,
                    PrimerNombreApoderado = proveedor.PrimerNombreApoderado,
                    SegundoNombreApoderado = proveedor.SegundoNombreApoderado,
                    PrimerApellidoApoderado = proveedor.PrimerApellidoApoderado,
                    SegundoApellidoApoderado = proveedor.SegundoApellidoApoderado,
                    CedulaApoderado = proveedor.CedulaApoderado,
                    FechaRige = proveedor.FechaRige,
                    FechaVence = proveedor.FechaVence,
                    Estado = proveedor.Estado,
                    DescripcionConvenio = proveedor.DescripcionConvenio,
                    BeneficioAsociado = proveedor.BeneficioAsociado,
                    BeneficioASEPBA = proveedor.BeneficioASEPBA,
                    DocumentoAdjunto = proveedor.DocumentoAdjunto,
                    PersonaContacto = proveedor.PersonaContacto,
                    CorreoContacto = proveedor.CorreoContacto,
                    TelefonoContacto = proveedor.TelefonoContacto,
                    SegundaPersonaContacto = proveedor.SegundaPersonaContacto,
                    CorreoSegundoContacto = proveedor.CorreoSegundoContacto,
                    TelefonoSegundoContacto = proveedor.TelefonoSegundoContacto,
                    Logo = proveedor.Logo,
                    UsuarioCreacion = User.Identity.Name,
                    FechaCreacion = DateTime.Now,
                    UsuarioModificacion = User.Identity.Name,
                    FechaModificacion = DateTime.Now
                };

SISASEPBA/SISASEPBA/Views/Proveedores/Create.cshtml
@model SISASEPBA.Models.Proveedor

@{
    ViewBag.Title = "Create";
}

<div class="panel panel-default">
    <div class="panel panel-heading">
        <strong>Crear proveedor</strong>
    </div>
    <div class="panel panel-body">
        @using (Html.BeginForm("Create", "Proveedores", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="col-md-6">

                <div class="form-group">
                    @Html.LabelFor(model => model.NumeroCedula, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NumeroCedula, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NumeroCedula, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NombreFantasia, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NombreFantasia, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NombreFantasia, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.NombreReal, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.NombreReal, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.NombreReal, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PrimerNombreApoderado, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PrimerNombreApoderado, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PrimerNombreApoderado, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SegundoNombreApoderado, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SegundoNombreApoderado, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SegundoNombreApoderado, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PrimerApellidoApoderado, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PrimerApellidoApoderado, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PrimerApellidoApoderado, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SegundoApellidoApoderado, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SegundoApellidoApoderado, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SegundoApellidoApoderado, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CedulaApoderado, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CedulaApoderado, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CedulaApoderado, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.FechaRige, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FechaRige, new { htmlAttributes = new { @class = "datepicker form-control", @type = "date" } })
                        @Html.ValidationMessageFor(model => model.FechaRige, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.FechaVence, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.FechaVence, new { htmlAttributes = new { @class = "datepicker form-control", @type = "date" } })
                        @Html.ValidationMessageFor(model => model.FechaVence, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.EditorFor(model => model.Estado)
                            @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

            </div>

            <div class="col-md-6">

                <div class="form-group">
                    @Html.LabelFor(model => model.DescripcionConvenio, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.DescripcionConvenio, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.DescripcionConvenio, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.BeneficioAsociado, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.BeneficioAsociado, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.BeneficioAsociado, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.BeneficioASEPBA, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.BeneficioASEPBA, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.BeneficioASEPBA, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.DocumentoAdjunto, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" class="form-control" id="Imagen" name="doc" />
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.PersonaContacto, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.PersonaContacto, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.PersonaContacto, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CorreoContacto, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CorreoContacto, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CorreoContacto, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TelefonoContacto, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TelefonoContacto, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TelefonoContacto, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.SegundaPersonaContacto, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.SegundaPersonaContacto, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.SegundaPersonaContacto, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.CorreoSegundoContacto, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.CorreoSegundoContacto, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.CorreoSegundoContacto, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.TelefonoSegundoContacto, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.TelefonoSegundoContacto, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.TelefonoSegundoContacto, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Logo, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" class="form-control" id="Imagen" name="img" />
                    </div>
                </div>

            </div>
            <div class="form-group">
                <div class="col-md-offset-4 col-md-10">
                    <input type="submit" value="Ingresar" class="btn btn-success" />
                    @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })
                </div>
            </div>
        </div>
            }

        </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SISASEPBA/SISASEPBA/Views/Proveedores/Index.cshtml
@model IEnumerable<SISASEPBA.Models.Proveedor>

@{
    ViewBag.Title = "Index";
}

<div class="panel panel-default">
    <div class="panel panel-heading">
        <strong>Catálogo de proveedores</strong>
    </div>
    <div class="panel panel-body">

        <p>
            @Html.ActionLink("Nuevo proveedor", "Create", null, new { @class = "btn btn-primary" })
        </p>

        <div class="table-responsive">
            <table class="table table-striped table-bordered" id="tablaProveedor">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.IdProveedor)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.NombreReal)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FechaRige)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.FechaVence)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Estado)
                        </th>
                       
                        <th>
                            Acción
                        </th>
                    </tr>
                </thead>

                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.IdProveedor)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.NombreReal)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FechaRige)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.FechaVence)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Estado)
                            </td>
                            <td>
                                @Html.ActionLink("Editar", "Edit", new { id = item.IdProveedor }, new { @class = "btn btn-danger" })
                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            //var rowsSelected = [];
            $('#tablaProveedor').DataTable({
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }

                }

            });
        });
    </script>
}