SISASEPBA/SISASEPBA/Models/EmpleadoConceptoNomina.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SISASEPBA.Models
{
    public class EmpleadoConceptoNomina
    {
        public string Accion { get; set; } = string.Empty;

        [DisplayName("Empleado")]
        [Required(ErrorMessage = "*Campo requerido.")]
        public int IdEmpleado { get; set; } = 0;

        [DisplayName("Concepto")]
        [Required(ErrorMessage = "*Campo requerido.")]
        public int IdConcepto { get; set; } = 0;

        [DisplayName("Nómina")]
        [Required(ErrorMessage = "*Campo requerido.")]
        public int IdNomina { get; set; } = 0;

        [DisplayName("Concepto por liquidación")]
        [Required(ErrorMessage = "*Campo requerido.")]
        public int IdConceptoLiquidacion { get; set; } = 0;

        [DisplayName("Consecutivo nómina")]
        [Required(ErrorMessage = "*Campo requerido.")]
        public int ConsecutivoNomina { get; set; } = 0;
        public int Cantidad { get; set; } = 0;
        public int Monto { get; set; } = 0;
        public int Total { get; set; } = 0;
        public string UsuarioCreacion { get; set; } = string.Empty;

        [DataType(DataType.Date)]
        public DateTime FechaCreacion { get; set; } = DateTime.Now;
        public string UsuarioModificacion { get; set; } = string.Empty;

        [DataType(DataType.Date)]
        public DateTime FechaModificacion { get; set; } = DateTime.Now;
    }
}

SISASEPBA/SISASEPBA/Controllers/EmpleadoConceptoNominaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Web;
using System.Web.Mvc;
using SISASEPBA.ServicioAsepba;

namespace SISASEPBA.Controllers
{
    [Authorize]
    public class EmpleadoConceptoNominaController : Controller
    {
        private readonly ServicioAsepba.ServiceAsepbaClient _servicio = new ServiceAsepbaClient();
        // GET: EmpleadoConceptoNomina
        public ActionResult Index()
        {
            ViewBag.Empleado = GetEmpleado();
            var dt = _servicio.ConsultarEmpleadoConceptoNomina(new EmpleadoConceptoNomina
            {
                Accion = "CONSULTAR",
                FechaCreacion = DateTime.Now,
                FechaModificacion = DateTime.Now
            });

            var usr = dt.Tables[0].AsEnumerable().Select(dataRow => new Models.EmpleadoConceptoNomina
            {
                IdEmpleado = dataRow.Field<int>("IDEMPLEADO"),
                IdConcepto = dataRow.Field<int>("IDCONCEPTO"),
                IdNomina = dataRow.Field<int>("IDNOMINA"),
                IdConceptoLiquidacion = dataRow.Field<int>("IDCONCEPTOLIQUIDACION"),
                ConsecutivoNomina = dataRow.Field<int>("CONSECUTIVONOMINA"),
                Cantidad = dataRow.Field<int>("CANTIDAD"),
                Monto = dataRow.Field<int>("MONTO"),
                Total = dataRow.Field<int>("TOTAL")

            }).ToList();

            return View(usr);
        }

        public List<Models.Empleado> GetEmpleado()
        {
            var dt = _servicio.ConsultarEmpleado(new Empleado
            {
                Accion = "CONSULTAR",
                FechaCreacion = DateTime.Now,
                FechaModificacion = DateTime.Now,
                FechaNacimiento = DateTime.Now,
                FechaIngreso = DateTime.Now,
                FechaSalida = DateTime.Now,
                UltimoCambioVac = DateTime.Now
            });

            var list = dt.Tables[0].AsEnumerable().Select(dataRow => new Models.Empleado
            {
                IdEmpleado = dataRow.Field<int>("IDEMPLEADO"),
                IdNacionalidad = dataRow.Field<string>("NACIONALIDAD"),
                IdDepartamento = dataRow.Field<string>("DEPARTAMENTO"),
                IdPuesto = dataRow.Field<string>("PUESTO"),
                IdNomina = dataRow.Field<string>("NOMINA"),
                IdFormaPago = dataRow.Field<string>("FORMAPAGO"),
                IdRegimenVacacional = dataRow.Field<string>("CONTROLVACACIONAL"),
                CodigoEmpleado = dataRow.Field<string>("CODIGOEMPLEADO"),
                PrimerNombre = dataRow.Field<string>("PRIMERNOMBRE"),
                SegundoNombre = dataRow.Field<string>("SEGUNDONOMBRE"),
                PrimerApellido = dataRow.Field<string>("PRIMERAPELLIDO"),
                SegundoApellido = dataRow.Field<string>("SEGUNDOAPELLIDO"),
                Estado = dataRow.Field<string>("ESTADO"),
                NumeroIdentificacion = dataRow.Field<int>("NUMEROIDENTIFICACION"),
                CorreoElectronico = dataRow.Field<string>("CORREOELECTRONICO"),
                TelefonoPrincipal = dataRow.Field<string>("TELEFONOPRINCIPAL")

            }).ToList();

            return list;
        }

        public List<Models.Nomina> GetNominas()
        {
            var dt = _servicio.ConsultarNomina(new Nomina
            {
                Accion = "CONSULTAR",
                FechaCreacion = DateTime.Now,
                FechaModificacion = DateTime.Now
            });

            var list = dt.Tables[0].AsEnumerable().Select(dataRow => new Models.Nomina
            {
                IdNomina = dataRow.Field<int>("IDNOMINA"),
                Alias = dataRow.Field<string>("ALIAS"),
                Descripcion = dataRow.Field<string>("DESCRIPCION"),
                Estado = dataRow.Field<string>("ESTADO"),

            }).ToList();

            return list;
        }


        // GET: EmpleadoConceptoNomina/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: EmpleadoConceptoNomina/Create
        public ActionResult Create()
        {
            ViewBag.ListaEmpleados = GetEmpleado();
            ViewBag.ListaNominas = GetNominas();
            return View();
        }

        // POST: EmpleadoConceptoNomina/Create
        [HttpPost]
        public ActionResult Create(Models.EmpleadoConceptoNomina EmpCN)
        {
            try
            {
                var objeto = new EmpleadoConceptoNomina
                {
                    Accion = "INSERTAR",
                    IdEmpleado = EmpCN.IdEmpleado,
                    IdConcepto = EmpCN.IdConcepto,
                    IdNomina = EmpCN.IdNomina,
                    IdConceptoLiquidacion = EmpCN.IdConceptoLiquidacion,
                    ConsecutivoNomina = EmpCN.ConsecutivoNomina,
                    Cantidad = EmpCN.Cantidad,
                    Monto = EmpCN.Monto,
                    Total = EmpCN.Total,
                    UsuarioCreacion = User.Identity.Name,
                    FechaCreacion = DateTime.Now,
                    UsuarioModificacion = User.Identity.Name,
                    FechaModificacion = DateTime.Now
                };

                var dt = _servicio.ProcesarEmpleadoConceptoNomina(objeto);

                if (dt.IsSuccess)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View("Create");
                }
            }
            catch
            {
                return View();
            }
        }

        // GET: EmpleadoConceptoNomina/Edit/5
        public ActionResult Edit(int id, int dato1, int dato2, int dato3)
        {
            ViewBag.ListaEmpleados = GetEmpleado();
            ViewBag.ListaNominas = GetNominas();
            var dt = _servicio.ConsultarEmpleadoConceptoNomina(new EmpleadoConceptoNomina
            {
                Accion = "CONSULTAR_CONCEPTO_NOMINA",
                IdEmpleado = id,
                IdConcepto = dato1,
                IdNomina = dato2,
                IdConceptoLiquidacion = dato3,
                FechaCreacion = DateTime.Now,
                FechaModificacion = DateTime.Now
            });
            var usr = dt.Tables[0].AsEnumerable().Select(dataRow => new Models.EmpleadoConceptoNomina
            {
                IdEmpleado = dataRow.Field<int>("IDEMPLEADO"),
                IdConcepto = dataRow.Field<int>("IDCONCEPTO"),
                IdNomina = dataRow.Field<int>("IDNOMINA"),
                IdConceptoLiquidacion = dataRow.Field<int>("IDCONCEPTOLIQUIDACION"),
                ConsecutivoNomina = dataRow.Field<int>("CONSECUTIVONOMINA"),
                Cantidad = dataRow.Field<int>("CANTIDAD"),
                Monto = dataRow.Field<int>("MONTO"),
                Total = dataRow.Field<int>("TOTAL"),
                UsuarioCreacion = dataRow.Field<string>("USUARIOCREACION"),
                FechaCreacion = dataRow.Field<DateTime>("FECHACREACION")


            }).FirstOrDefault();

            return View(usr);
        }

        // POST: EmpleadoConceptoNomina/Edit/5
        [HttpPost]
        public ActionResult Edit(Models.EmpleadoConceptoNomina EmpCN)
        {
            try
            {
                var objeto = new EmpleadoConceptoNomina
                {
                    Accion = "ACTUALIZAR",
                    IdEmpleado = EmpCN.IdEmpleado,
                    IdConcepto = EmpCN.IdConcepto,
                    IdNomina = EmpCN.IdNomina,
                    IdConceptoLiquidacion = EmpCN.IdConceptoLiquidacion,
                    ConsecutivoNomina = EmpCN.ConsecutivoNomina,
                    Cantidad = EmpCN.Cantidad,
                    Monto = EmpCN.Monto,
                    Total = EmpCN.Total,
                    UsuarioCreacion = User.Identity.Name,
                    FechaCreacion = DateTime.Now,
                    UsuarioModificacion = User.Identity.Name,
                    FechaModificacion = DateTime.Now
                };
                var dt = _servicio.ProcesarEmpleadoConceptoNomina(objeto);

                if (dt.IsSuccess)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View("Edit");
                }
            }
            catch
            {
                return View();
            }
        }

        
    }
}

SISASEPBA/SISASEPBA/Views/EmpleadoConceptoNomina/Create.cshtml
@model SISASEPBA.Models.EmpleadoConceptoNomina

@{
    ViewBag.Title = "Create";
}

<div class="panel panel-default">
    <div class="panel panel-heading">
        <strong>Crear concepto por nómina de empleado</strong>
    </div>
    <div class="panel panel-body">

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="col-md-6">
                <div class="form-group">
                    @Html.LabelFor(model => model.IdEmpleado, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.IdEmpleado, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.IdEmpleado, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IdConcepto, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.IdConcepto, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.IdConcepto, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IdNomina, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.IdNomina, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.IdNomina, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.IdConceptoLiquidacion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.IdConceptoLiquidacion, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.IdConceptoLiquidacion, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="col-md-6">

                <div class="form-group">
                    @Html.LabelFor(model => model.ConsecutivoNomina, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ConsecutivoNomina, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ConsecutivoNomina, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Monto, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Monto, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Monto, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
                <div class="form-group">
                    <div class="col-md-offset-4 col-md-10">
                        <input type="submit" value="Ingresar" class="btn btn-success" />
                        @Html.ActionLink("Regresar", "Index", null, new { @class = "btn btn-danger" })
                    </div>
                </div>
            </div>
            }
        </div>

</div>

SISASEPBA/SISASEPBA/Views/EmpleadoConceptoNomina/Edit.cshtml
@model SISASEPBA.Models.EmpleadoConceptoNomina

@{
    ViewBag.Title = "Edit";
}

<div class="panel panel-default">
    <div class="panel panel-heading">
        <strong>Editar</strong>
    </div>
    <div class="panel panel-body">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="col-md-6">
                <div class="form-group">
                    @Html.HiddenFor(model => model.IdEmpleado, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.HiddenFor(model => model.IdEmpleado, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    @Html.HiddenFor(model => model.IdConcepto, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.HiddenFor(model => model.IdConcepto, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    @Html.HiddenFor(model => model.IdNomina, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.HiddenFor(model => model.IdNomina, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="form-group">
                    @Html.HiddenFor(model => model.IdConceptoLiquidacion, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.HiddenFor(model => model.IdConceptoLiquidacion, new { htmlAttributes = new { @class = "form-control" } })
                    </div>
                </div>
            </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ConsecutivoNomina, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ConsecutivoNomina, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ConsecutivoNomina, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Cantidad, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Monto, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Monto, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Monto, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Total, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-4 col-md-6">
                        <input type="submit" value="Guardar cambios" class="btn btn-success" />
                        @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-danger" })
                    </div>
                </div>
            </div>
            }

        </div>
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SISASEPBA/SISASEPBA/Views/EmpleadoConceptoNomina/Index.cshtml
@model IEnumerable<SISASEPBA.Models.EmpleadoConceptoNomina>

@{
    ViewBag.Title = "Index";
}

<div class="panel panel-default">
    <div class="panel panel-heading">
        <strong>Empleados conceptos por nómina</strong>
    </div>
    <div class="panel panel-body">

        <p>
            @Html.ActionLink("Ingresar empleado conceptos por nómina", "Create", "EmpleadoConceptoNomina", null, new { @class = "btn btn-primary" })
        </p> <br />

        <div class="table-responsive">

            <table class="table table-striped table-bordered" id="tablaEmpleadoConceptoNomina">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.IdEmpleado)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.IdConcepto)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.IdNomina)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.ConsecutivoNomina)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Cantidad)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Monto)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Total)
                        </th>
                        <th>
                            Acción
                        </th>
                    </tr>
                </thead>

                <tbody>

                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.IdEmpleado)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IdConcepto)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.IdNomina)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ConsecutivoNomina)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Cantidad)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Monto)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Total)
                            </td>
                            <td>
                                @Html.ActionLink("Editar", "Edit", new { id=item.IdEmpleado, dato1= item.IdConcepto, dato2=item.IdNomina, dato3= item.IdConceptoLiquidacion },new {@class ="btn btn-danger" })
                            </td>
                        </tr>
                    }
                </tbody>

            </table>
        </div>


    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            //var rowsSelected = [];
            $('#tablaEmpleadoConceptoNomina').DataTable({
                "language": {
                    "sProcessing": "Procesando...",
                    "sLengthMenu": "Mostrar _MENU_ registros",
                    "sZeroRecords": "No se encontraron resultados",
                    "sEmptyTable": "Ningún dato disponible en esta tabla",
                    "sInfo": "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    "sInfoEmpty": "Mostrando registros del 0 al 0 de un total de 0 registros",
                    "sInfoFiltered": "(filtrado de un total de _MAX_ registros)",
                    "sInfoPostFix": "",
                    "sSearch": "Buscar:",
                    "sUrl": "",
                    "sInfoThousands": ",",
                    "sLoadingRecords": "Cargando...",
                    "oPaginate": {
                        "sFirst": "Primero",
                        "sLast": "Último",
                        "sNext": "Siguiente",
                        "sPrevious": "Anterior"
                    },
                    "oAria": {
                        "sSortAscending": ": Activar para ordenar la columna de manera ascendente",
                        "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                    }

                }

            });
        });
    </script>
}